---
driver_config:
  digitalocean_access_token: <%= ENV['DIGITALOCEAN_ACCESS_TOKEN'] %>

provisioner:
  name: chef_zero
  data_path: test/shared
  solo_rb:
    ssl_verify_mode: verify_peer
  require_chef_omnibus: latest

platforms:
- name: debian-7-8-x64
  driver_plugin: digitalocean
  driver_config:
    region: ams3
    size: 512mb
    ssh_key_ids: <%= ENV['DIGITALOCEAN_SSH_KEY_IDS'] %>
    ssh_key: <%= ENV['DIGITALOCEAN_SSH_KEY_PATH'] %>
- name: ubuntu-14-04-1-x64
  driver_plugin: digitalocean
  driver_config:
    region: ams3
    size: 512mb
    ssh_key_ids: <%= ENV['DIGITALOCEAN_SSH_KEY_IDS'] %>
    ssh_key: <%= ENV['DIGITALOCEAN_SSH_KEY_PATH'] %>

suites:
- name: default
  data_bags_path: test/integration/default/data_bags
  encrypted_data_bag_secret_key_path: .data_bags/insecure_databag_secret
  run_list:
    - recipe[dop_mysql::default]
    - recipe[dop_mysql::percona_tools]
    - recipe[dop_mysql::automysqlbackup]
    - recipe[dop_mysql::mysqltuner]
    - recipe[dop_mysql::mysqlreport]
  attributes: {
    "mysql": {
      "bind_address": "127.0.0.1",
      "port": "3306",
      "custom_cnf": {
        "mysqld": {
          "bind-address": "127.0.0.1"
        }
      }
    }
  }