---
driver:
  name: vagrant
  driver_config:
    require_chef_omnibus: latest

provisioner:
  name: chef_zero
  data_path: test/shared
  solo_rb:
    ssl_verify_mode: verify_peer

platforms:
- name: debian-7.9.0-amd64
  driver_config:
    box: ffuenf/debian-7.9.0-amd64
    box_url: https://atlas.hashicorp.com/ffuenf/debian-7.9.0-amd64

- name: ubuntu-14.04.3-server-amd64
  driver_config:
    box: ffuenf/ubuntu-14.04.3-server-amd64
    box_url: https://atlas.hashicorp.com/ffuenf/ubuntu-14.04.3-server-amd64

suites:
- name: default
  data_bags_path: test/integration/default/data_bags
  encrypted_data_bag_secret_key_path: .data_bags/insecure_databag_secret
  run_list:
    - recipe[dop_mysql::default]
    - recipe[dop_mysql::percona_tools]
    - recipe[dop_mysql::automysqlbackup]
    - recipe[dop_mysql::mysqltuner]
    - recipe[dop_mysql::mysqlreport]
  attributes: {
    "mysql": {
      "bind_address": "127.0.0.1",
      "port": "3306",
      "custom_cnf": {
        "mysqld": {
          "bind-address": "127.0.0.1"
        }
      }
    }
  }